server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/users/ {
        proxy_pass http://user-service:3001/users/;
    }

    location /api/products/ {
        proxy_pass http://product-service:3002/products/;
    }

    location /api/filter/ {
        proxy_pass http://product-service:3002/filter/;
    }

    location /api/cart/ {
        proxy_pass http://cart-service:3003/cart/;
    }
}