apiVersion: apps/v1
kind: Deployment

metadata:
  name: cart-deployment
  namespace: ecommerce

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cart-service

  template:
    metadata:
      labels:
        app: cart-service

    spec:
      containers:
        - name: cart-service
          image: ecommerce-cart:v1
          imagePullPolicy: Never

          command: ["node"]
          args: ["server.js"]

          ports:
            - containerPort: 3003

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: CART_PORT

            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: NODE_ENV

            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: MONGO_USERNAME

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: MONGO_PASSWORD

            - name: MONGO_CLUSTER
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: MONGO_CLUSTER

            - name: MONGO_DBNAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: MONGO_DBNAME

            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: ACCESS_TOKEN